version: '3.8'
services:
  myresumedb:
    build:
      context: ./db
      #image: sirinehassine/myresumedb
    ports:
      - "3306:3306"
    volumes:
      - myresumedbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myresumepass

  myresumeapp:
    build:
      context: ./app
    #image: sirinehassine/myresumeapp
    ports:
      - "8080:8080"
    volumes:
      - myresumeappdata:/usr/local/tomcat/webapps
    depends_on:
      -  myresumedb
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=myresumedb:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    
  myresumeweb:
    build:
      context: ./web
      #image: sirinehassine/myresumeweb
    ports:
      - "80:80"
volumes:
  myresumedbdata: {}
  myresumeappdata: {}
