version: '3.8'
services:
  myresumedb:
    build:
      context: ./db
      #image: sirinehassine/myresumedb
    ports:
      - "3306:3306"
    volumes:
      - myresumedbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myresumepass
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pmyresumepass", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s

  myresumeapp:
    build:
      context: ./app
    #image: sirinehassine/myresumeapp
    ports:
      - "8080:8080"
    volumes:
      - myresumeappdata:/usr/local/tomcat/webapps
    depends_on:
      myresumedb:
        condition: service_healthy
    
  myresumeweb:
    build:
      context: ./web
      #image: sirinehassine/myresumeweb
    ports:
      - "80:80"
volumes:
  myresumedbdata: {}
  myresumeappdata: {}
