version: '3.8'
services:
  myresumedb:
    build:
      context: ./db
      #image: sirinehassine/myresumedb
    ports
      - "3306:3306"
    volumes:
      - myresumedbdata:/var/lib/mysql

  myresumeapp:
    build:
      context: ./app
    #image: sirinehassine/myresumeapp
    ports:
      - "8080:8080"
    volumes:
      - myresumeappdata:/usr/local/tomcat/webapps

  myresumeweb:
    build:
      context: ./web
      #image: sirinehassine/myresumeweb
    ports:
      - "80:80"
volumes:
  myresumedbdata: {}
  myresumeappdata: {}

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
DockerFiles/docker-compose.yml[+] [dos] (13:56 05/11/2024)                                                                            5,10 All
-- INSERT --

