version: '3.8'
services:
  myresumedb:
    container_name: myresumedb
    build:
      context: ./db
    image: sirinehassine/myresumedb
    ports:
      - "3306:3306"
    volumes:
      - myresumedbdata:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}		
        TZ: ${TZ}
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "--execute", "SHOW DATABASES;"]
      interval: 10s
      retries: 5
      timeout: 5s

  myresumeapp:
    container_name: myresumeapp
    build:
      context: ./app
    image: sirinehassine/myresumeapp
    ports:
      - "8080:8080"
    volumes:
      - myresumeappdata:/usr/local/tomcat/webapps
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PROTOCOL: ${MAIL_PROTOCOL}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_TO: ${MAIL_TO}

    depends_on:
      myresumedb:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "http://${APP_HOST}:8080"]
        interval: 10s
        retries: 5
        timeout: 5s
    
  myresumeweb:
    container_name: myresumeweb
    build:
      context: ./web
    image: sirinehassine/myresumeweb
    depends_on: 
      myresumeapp:
            condition: service_healthy
    ports:
      - "80:80"
volumes:
  myresumedbdata: {}
  myresumeappdata: {}
