FROM mysql:8.0.33
LABEL "Project"="MyResume"
LABEL "Author"="Sirine"

ENV MYSQL_ROOT_PASSWORD="myresumepass"
ENV MYSQL_DATABASE="myresume"
ENV TZ="Europe/Paris"


COPY db_backup.sql docker-entrypoint-initdb.d/db_backup.sql
